/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedog.rainbow.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
