/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedog.rainbow.world;

public class App {

    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
